name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        dir: [tests]
        platform: [ubuntu-latest]
        node: ['14.x']
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: yarn
      working-directory: ${{ matrix.dir }}
    - run: npx playwright install 
      working-directory: ${{ matrix.dir }}  
    - run: xvfb-run --auto-servernum -- yarn test
      working-directory: ${{ matrix.dir }}
      env:
        SKIP_PREFLIGHT_CHECK: "true"
    - name: upload artifact
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-day: 30
    - name: Coveralls
      uses: coverallsapp/github-action@master
      if: ${{ matrix.dir == 'create-react-app-coverage' }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: create-react-app-coverage/coverage/lcov.info
        base-path: ${{ matrix.dir }} 